config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  root to: 'pages#home'

  get 'home', to: 'pages#home', as: :home
  get 'about', to: 'pages#about', as: :about
  get 'cv', to: 'pages#cv', as: :cv

  resources :stories
  resources :projects
  resources :publications
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/publication.rb
class Publication < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/story.rb
class Story < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @stories = Story.all
  end

  def cv
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path(@project)
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to projects_path
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :collaborators, :notes, :photo)
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @publications = Publication.all
  end

  def new
    @publication = Publication.new
  end

  def create
    @publication = Publication.new(publication_params)
    @publication.date = Date.today
    if @publication.save
      redirect_to publications_path(@publication)
    else
      render :new
    end
  end

  def show
    @publication = Publication.find(params[:id])
  end

  def edit
    @publication = Publication.find(params[:id])
  end

  def update
    @publication = Publication.find(params[:id])
    @publication.update(publciation_params)
  end

  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy
    redirect_to publications_path
  end

  private

  def publication_params
    params.require(:publication).permit(:name, :description, :collaborators, :journal, :photo)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :one_user_registered?, only: [:new, :create]

  def new
    super
  end

  def create
    super
  end

  def update
    super
  end

  protected

  def one_user_registered?
    if User.count == 1
      if user_signed_in?
        redirect_to root_path
      else
        redirect_to new_user_session_path
      end
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @stories = Story.all
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.date = Date.today
    if @story.save
      redirect_to stories_path(@story)
    else
      render :new
    end
  end

  def show
    @story = Story.find(params[:id])
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])
    @story.update(story_params)
    redirect_to story_path(params[:id])
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to stories_path
  end

  private

  def story_params
    params.require(:story).permit(:name, :paragraph, :website)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Andrew Brown</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <div id="particles-js"></div>
  <body style="background-color: #FFFFFF;">
    <%= render 'shared/navbar' %>
      <%= yield %>
    <%= render 'shared/footer' %>
    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/pages/cv.html.erb
<div class="container">
  <div class="CV-container">
    <h1>Curriculum Vitae</h1>
    <hr/>
    <%= image_tag 'CV.png' %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/homepage_banner' %>
<div class="container">
  <h3>News</h3>
  <hr>
  <div class="stories-card-container">
    <% @stories.each do |story| %>
      <% if current_user %>
        <%= link_to story_path(story.id), method: :get do %>
          <%= render "shared/story_card", story: story %>
        <% end %>
      <% else %>
        <%= render "shared/story_card", story: story %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="wrapper">
  <div class="project-edit-container">
    <h1>Edit <%= @project.name %></h1>
    <div class="link-flex-box">
      <%= render 'shared/project_form', project: @project %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="wrapper">
  <div class="projects-banner-container">
    <%= render "shared/projects_banner" %>
  </div>
  <div class="projects-card-container">
    <div class="row">
      <% @projects.each do |project| %>
        <div class="col-xs-12 col-sm-6 col-md-6">
          <% if current_user %>
            <%= link_to project_path(project.id), method: :get do %>
              <%= render "shared/project_card", project: project %>
            <% end %>
          <% else %>
            <%= render "shared/project_card", project: project %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="wrapper">
  <div class="project-new-container">
    <h1>New Project</h1>
    <div class="link-flex-box">
      <%= render 'shared/project_form', project: @project %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="wrapper">
  <div class="project-show-container">
    <h1><%= @project.name %></h1>
    <div class="link-flex-box">
      <%= link_to "Delete", project_path, method: :delete %>
      <%= link_to "Edit", edit_project_path %>
    </div>
  </div>
</div>

app/views/publications/edit.html.erb
<div class="wrapper">
  <div class="publication-edit-container">
    <h1>Edit <%= @publication.name %></h1>
    <div class="link-flex-box">
      <%= render 'shared/publication_form', publication: @publication %>
    </div>
  </div>
</div>

app/views/publications/index.html.erb
<div class="wrapper">
  <div class="publications-banner-container">
    <%= render "shared/publications_banner" %>
  </div>
  <div class="publications-card-container">
    <div class="row">
      <% @publications.each do |publication| %>
        <div class="col-xs-12 col-sm-6 col-md-6">
          <% if current_user %>
            <%= link_to publication_path(publication.id), method: :get do %>
              <%= render "shared/publication_card", publication: publication %>
            <% end %>
          <% else %>
            <%= render "shared/publication_card", publication: publication %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/publications/new.html.erb
<div class="wrapper">
  <div class="publication-new-container">
    <h1>New Publication</h1>
    <div class="link-flex-box">
      <%= render 'shared/publication_form', publication: @publication %>
    </div>
  </div>
</div>

app/views/publications/show.html.erb
<div class="wrapper">
  <div class="publication-show-container">
    <h1><%= @publication.name %></h1>
    <div class="link-flex-box">
      <%= link_to "Delete", publication_path, method: :delete %>
      <%= link_to "Edit", edit_publication_path %>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Andrew Brown</h1>
    <hr/>
    <h4>DPhil Student</h4>
    <h4>Visual Geometry Group</h4>
    <h4>University of Oxford</h4>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/Andrew-Brown1?fbclid=IwAR1gy0B5w43AguSnu4CgMtpdySSFkE3uX9ekXUPs683OLIh2x-MXGfSmHfk"><i class="fab fa-github"></i></a>
    <a href="https://uk.linkedin.com/in/andrew-brown-6b4193115"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-sign-in">
    <% if user_signed_in? %>
      <div class="user-actions">
        <div class="new-story">
          <% if current_user %>
            <%= link_to 'New Story', new_story_path %>
          <% end %>
        </div>
        <div class="new-project">
          <% if current_user %>
            <%= link_to 'New Project', new_project_path %>
          <% end %>
        </div>
        <div class="new-publication">
          <% if current_user %>
            <%= link_to 'New Publication', new_publication_path %>
          <% end %>
        </div>
        <div class='sign-out'>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link footer-andrew-brown-sign-out" %>
        </div>
      </div>
    <% else %>
      <div class="sign-in">
        <%= link_to 'Sign In', new_user_session_path, class: "navbar-wagon-item navbar-wagon-link footer-andrew-brown-sign-out" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_homepage_banner.html.erb
<div class="banner">
  <div class="profile_image">
    <%= image_tag "andrewprofilepic.png", class:"rounded"%>
  </div>
  <div class="profile">
    <div class="profile_info">
      <h1>Andrew Brown</h1>
      <h4>abrown@robots.ox.ac.uk</h4>
      <div class="text-container">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-andrew-brown navbar-fixed-top">
  <!-- <a href="http://www.ox.ac.uk/" class="navbar-andrew-brown-logo">
    <%= image_tag 'university-of-oxford-logo.png' %>
  </a> -->

  <!-- Fill out empty space left by logo -->
  <a href="" class="navbar-andrew-brown-logo"></a>

  <div class="navbar-andrew-brown-right hidden-xs hidden-sm">
    <%= link_to "Home", root_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link' %>
<!--     <%= link_to "About", about_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link' %> -->
<!--     <%= link_to "News", stories_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link' %> -->
    <%= link_to "Projects", projects_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link' %>
    <%= link_to "Publications", publications_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link' %>
    <%= link_to "CV", cv_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link' %>

    <!-- Profile picture -->
<!--     <div class="navbar-andrew-brown-item">
      <div class="navbar-andrew-brown-right hidden-xs hidden-sm">
        <%= link_to "Andrew Brown", root_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link navbar-andrew-brown-name-link' %>
      </div> -->
    </div>
  </div>
  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-andrew-brown-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-andrew-brown-dropdown-menu">
        <li><%= link_to "Home", root_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link' %></li>
        <li><%= link_to "About", about_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link' %></li>
        <li><%= link_to "News", stories_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link' %></li>
        <li><%= link_to "Projects", projects_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link' %></li>
        <li><%= link_to "Publications", publications_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link' %></li>
        <li><%= link_to "CV", cv_path, class: 'navbar-andrew-brown-item navbar-andrew-brown-link' %></li>
      </ul>
    </div>
  </div>

</div>

app/views/shared/_project_card.html.erb
<div class="example-2 project-card">
  <% if project.photo? %>
  <div class="project-card-wrapper" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path project.photo, width: 700, height: 600, crop: :fit%>')">
  <% end %>
    <div class="project-data">
      <div class="project-content">
        <span class="project-name"><%= project.name %></span>
        <h1 class="project-description"><%= project.description %></h1>
        <p class="project-collaborators"><%= project.collaborators %></p>
        <p class="project-notes"><%= project.notes %></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_project_form.html.erb
<%= simple_form_for(project) do |p| %>
  <%= p.input :name,
              label: "Name of Project",
              input_html: { class: "edit-form-style" } %>
  <%= p.input :description,
              label: "Brief Description of Project",
              input_html: { class: "edit-form-style" } %>
  <%= p.input :collaborators,
              label: "Project Collaborators",
              input_html: { class: "edit-form-style" } %>
  <%= p.input :notes,
              label: "Details of Project",
              input_html: { class: "edit-form-style" } %>
  <%= p.input :photo %>
  <%= p.input :photo_cache, as: :hidden %>
  <%= p.submit %>
<% end %>

app/views/shared/_projects_banner.html.erb
<div class="projects-banner">
  <div class="projects-banner-content">
    <h1>Projects</h1>
    <hr/>
  </div>
</div>

app/views/shared/_publication_card.html.erb
<div class="example-2 publication-card">
  <% if publication.photo? %>
  <div class="publication-card-wrapper" style="
  background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path publication.photo, height: 300, width: 400, crop: :limit %>')">
  <% end %>
    <div class="publication-data">
      <div class="publication-content">
        <span class="publication-name"><%= publication.name %></span>
        <h1 class="publication-description"><%= publication.description %></h1>
        <p class="publication-collaborators"><%= publication.collaborators %></p>
        <p class="publication-notes"><%= publication.journal %></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_publication_form.html.erb
<%= simple_form_for(publication) do |p| %>
  <%= p.input :name,
              label: "Name of Publication",
              input_html: { class: "edit-form-style" } %>
  <%= p.input :description,
              label: "Brief Description of Publication",
              input_html: { class: "edit-form-style" } %>
  <%= p.input :collaborators,
              label: "Publication Collaborators",
              input_html: { class: "edit-form-style" } %>
  <%= p.input :journal,
              label: "Journal Published In",
              input_html: { class: "edit-form-style" } %>
  <%= p.input :photo %>
  <%= p.input :photo_cache, as: :hidden %>
  <%= p.submit %>
<% end %>

app/views/shared/_publications_banner.html.erb
<div class="publications-banner">
  <div class="publications-banner-content">
    <h1>Publications</h1>
    <hr/>
    <h4>Watch this space...</h4>
  </div>
</div>

app/views/shared/_stories_banner.html.erb
<div class="stories-banner">
  <div class="stories-banner-content">
    <h1>News</h1>
    <hr/>
  </div>
</div>

app/views/shared/_story_card.html.erb
<div class="story">
  <div class="story-name">
    <h3><%= story.name %></h3>
    <p><%= story.date %></p>
  </div>
  <div class="story-body">
    <p>
      <%= story.paragraph %>
    </p>
  </div>
  <div class="story-link">
    <p class="status pending"><%= story.website %></p>
  </div>
</div>

app/views/shared/_story_form.html.erb
<%= simple_form_for(story) do |s| %>
  <%= s.input :name,
              label: "Header",
              input_html: { class: "edit-form-style" } %>
  <%= s.input :paragraph,
              label: "Brief Description",
              input_html: { class: "edit-form-style" } %>
  <%= s.input :website,
              label: "Link",
              input_html: { class: "edit-form-style" } %>
  <%= s.submit %>
<% end %>

app/views/stories/edit.html.erb
<div class="wrapper">
  <div class="story-edit-container">
    <h1>Edit <%= @story.name %></h1>
    <div class="link-flex-box">
      <%= render 'shared/story_form', story: @story %>
    </div>
  </div>
</div>

app/views/stories/index.html.erb
<div class="container">
  <div class="stories-banner-container">
    <%= render "shared/stories_banner" %>
  </div>
  <div class="stories-card-container">
    <% @stories.each do |story| %>
      <% if current_user %>
        <%= link_to story_path(story.id), method: :get do %>
          <%= render "shared/story_card", story: story %>
        <% end %>
      <% else %>
        <%= render "shared/story_card", story: story %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/stories/new.html.erb
<div class="wrapper">
  <div class="story-new-container">
    <h1>New Story</h1>
    <div class="link-flex-box">
      <%= render 'shared/story_form', story: @story %>
    </div>
  </div>
</div>

app/views/stories/show.html.erb
<div class="wrapper">
  <div class="story-show-container">
    <h1><%= @story.name %></h1>
    <div class="link-flex-box">
      <%= link_to "Delete", story_path, method: :delete %>
      <%= link_to "Edit", edit_story_path %>
    </div>
  </div>
</div>